#! /bin/sh

# _ROOT: 工作目录
# ROOT: 总是正确指向自身所在目录
_ROOT="$(pwd)" && cd "$(dirname "$0")" && ROOT="$(pwd)"

APPNAME="$(basename "$0")"
TARGET="$ROOT/bin/$APPNAME"

export MAINFILE="$ROOT/main.go"
# disable optimization, useful for dlv debugging
#export DEVELOP=1

# build && run
"$ROOT/build" "$APPNAME" "$TARGET" && "$TARGET" $*
