#! /bin/sh

# ---------------------------- Configure ----------------------------
if [ -z "$1" ]; then
    echo "Usage: $0 {the appname}"
    echo "e.g. $0 foo"
    exit 1
fi

APPNAME="$1"
# ------------------------------- Run -------------------------------

_ROOT="$(pwd)" && cd "$(dirname "$0")" && ROOT="$(pwd)"

sedi () {
    sed --version >/dev/null 2>&1 && sed -i -- "$@" || sed -i "" "$@"
}

# update file name
find . | grep -v '^\./\.git/' | while read f; do
    b="$(basename "$f")"
    if echo "$b"|grep -qF '{=APPNAME=}'; then
        mv "$f" "$(dirname "$f")/$(echo "$b" | sed -n "s;{=APPNAME=};$APPNAME;p")"
    fi
done

# update file content
find . -type f | grep -v '^\./\.git/' | egrep -v '^\./init' | while read f; do
    sedi "s;{=APPNAME=};$APPNAME;g" $f
done

ln -sf utils/build "$APPNAME"

echo "Success!"
echo "Please remove [me] and the extra [.git] dir by your hands"
