#! /bin/sh

# _ROOT: 工作目录
# ROOT: 总是正确指向本脚本所在目录
_ROOT="$(pwd)" && cd "$(dirname "$0")" && ROOT="$(pwd)"

APPNAME=go-skel
PJROOT="$(dirname "$(dirname "$ROOT")")"
VERSION="0.0.1"
RELEASE=1
if which git 2>/dev/null > /dev/null && git status 2>/dev/null >/dev/null; then
    GIT_HASH="$(git log -n1 --pretty=format:%H 2>/dev/null | head -c7)"
    TAG_NAME="$(git describe --long --match v[0-9]* 2>/dev/null | grep -oP '.*(?=-\d+-g.{7,}$)')"
    if [ -n "$TAG_NAME" ]; then
        TAG_HASH="$(git tag -l "$TAG_NAME" --format '%(object)')"
        TAG_DIFF="$(git rev-list --count HEAD ^$TAG_HASH)"

        VERSION="$(echo $TAG_NAME | cut -c2-)"
        RELEASE="$((1+TAG_DIFF))"
    fi
    RELEASE="$RELEASE.$GIT_HASH"
fi
RUNROOT="/opt/$APPNAME"

RPMBUILD="$_ROOT/_rpmbuild"
SPECFILE="$RPMBUILD/$APPNAME.spec"

if [ -n "$1" ]; then
    if [ "$1" = "help" ]; then
        echo "Usage: $0"
        echo "or $0 clean"
        exit
    fi
    if [ "$1" = "clean" ]; then
        rm -rf "$RPMBUILD"
        rm -rf *.rpm
        exit
    fi
fi

# clean
rm -rf "$RPMBUILD"

# prepare
mkdir -p "$RPMBUILD"
cp "$ROOT/$APPNAME.spec" "$SPECFILE"
sed -i 's;^\(\s*%define\s\+name\s\+\).\+;\1'$APPNAME';' "$SPECFILE"
sed -i 's;^\(\s*%define\s\+version\s\+\).\+;\1'$VERSION';' "$SPECFILE"
sed -i 's;^\(\s*%define\s\+release\s\+\).\+;\1'$RELEASE';' "$SPECFILE"
sed -i 's;^\(\s*%define\s\+pjroot\s\+\).\+;\1'$PJROOT';' "$SPECFILE"
sed -i 's;^\(\s*%define\s\+runroot\s\+\).\+;\1'$RUNROOT';' "$SPECFILE"

# build
rpmbuild --define "_topdir $RPMBUILD" -bb "$SPECFILE"

# move
find "$RPMBUILD/RPMS" -name '*.rpm' | xargs -I{} mv {} "$_ROOT/"
