#!/bin/sh
set -e

case "$1" in
  abort-upgrade|abort-remove|abort-deconfigure|configure)
    ;;  

  *)  
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;  
esac

if [ -x /etc/init.d/{=BINARY_NAME=} ]; then
  if [ -s {=PID_DIR=}/{=BINARY_NAME=}.pid ] && pidof {=INSTALL_DIR=}/bin/{=BINARY_NAME=} >/dev/null; then
    if ! invoke-rc.d {=BINARY_NAME=} stop; then
      SRV_PID=`cat {=PID_DIR=}/{=BINARY_NAME=}.pid`
      kill -s KILL "$SRV_PID"
    fi
    invoke-rc.d {=BINARY_NAME=} start || exit $?
  else
    invoke-rc.d {=BINARY_NAME=} start || exit $?
    update-rc.d -f {=BINARY_NAME=} defaults
  fi  
fi



exit 0
